### ISSUE TITLE
Need HTML Snippet

### ISSUE THREAD

**Issue by pxwee5** [adrhumphreys/vscode-silverstripe#10]
I've added Silverstripe into VScode and while I have all the snippets setup for SilverStripe. I lost all the HTML snippets. 

Is there a way to inherit the snippets from HTML file types?

**Comment by microcipcip** [comment]
@pxwee5 go to "Settings > User snippets" and search for "emmet.includeLanguages". Then add this configuration in the JSON file:
```
{
  "emmet.includeLanguages": {
    "SilverStripe": "html"
  }
}
```
