### ISSUE TITLE
Feature Suggestion: Go to Definition

### ISSUE THREAD

**Issue by b-rhodes** [adrhumphreys/vscode-silverstripe#14]
With VSCode (and PHP Storm) you can use cmd/ctrl + click to navigate to a PHP class definition if you click on a place that it's used in the code.
In PHP Storm this also works inside silverstripe template files, if you click on the name inside an include tag.
For example:
if you were to use cmd+click on the text "PageHead" inside this: `<% include PageHead %>`, then the editor would attempt to navigate to the `PageHead.ss` file.
This would be super useful functionality to add for larger sites with more template files.

Sorry if this is the wrong place to suggest this, I'm not even sure if it's possible, I'm not well versed in vscode plugins.

**Comment by b-rhodes** [comment]
https://github.com/raket/idea-silverstripe
This is the phpstorm plugin that adds silverstripe template language support.

**Comment by gorriecoe** [comment]
@b-rhodes Development for this feature has started =) https://github.com/adrhumphreys/vscode-silverstripe/tree/Add/feature-go-to-definition

**Comment by b-rhodes** [comment]
Awesome!

**Comment by gorriecoe** [comment]
This has been added to 1.0.6
