### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by lekoala** [adrhumphreys/vscode-silverstripe#2]
it seems that using this, it removes the ability to format html. any idea how to handle this?

by simply setting the association in   "files.associations" I can format .ss files, but obviously snippets and colors are gone.

**Comment by adrhumphreys** [comment]
@lekoala I looked into it at one point and found that it was very hard to make it work with normal snippets, etc. I had a look around at other extensions to see how they dealt with it but couldn't find any that had. To make it work you'd need to get the language server written for html and then extend it to work with ss files.

As far as I know that's the only way to do it, I could easily be wrong though
