### ISSUE TITLE
HTML Formatting

### ISSUE THREAD

**Issue by egeis** [adrhumphreys/vscode-silverstripe#3]
I noticed that the formatting breaks on the "id" html attribute. Escaping the the equals restores formatting.  As far as I can tell so far It only occurs on that tag, If I experience any other issues related to formatting caused by attributes I'll add them here.

Broken:
`<div class="row" id="MainContent">...blah.blah.blah...</div>`

Temporary fix: 
`<div class="row" id\="MainContent">...blah.blah.blah...</div>`

Edited: Forgot to escape my sample code...

**Comment by beshad** [comment]
about the problem above, there is a line in the silverstripe.tmLanguage XML file located in .vscode/extentions folder. the line is <string>\b(id)\b\s*(=)</string> just remove the * after letter 's' and it fixes the breaking on id problem.

**Comment by pxwee5** [comment]
This needs to be fixed.
