### ISSUE TITLE
Commenting Shortcut

### ISSUE THREAD

**Issue by andrewhoule** [adrhumphreys/vscode-silverstripe#4]
Would be helpful if you could use the commenting shortcut for a line, just like HTML syntax... e.g. cmd+/ would comment the whole line.

**Comment by kabadesu** [comment]
@andrewhoule have you got block comments working with this extension? If so, how did you do it?

I can't get either style of comment to work inside `.ss` files.

**Comment by andrewhoule** [comment]
No :(  I went back to Sublime Text... for now.
